import { describe, expect, it } from "vitest";
import { deployToolNames } from "../../../../src/products/deploy/tools/index.js";

const coveredDeployToolNames = [
  "deploy_add_v4_environment_hosts",
  "deploy_cancel_v4_deploy_record",
  "deploy_create_application",
  "deploy_create_environment",
  "deploy_create_task_by_template",
  "deploy_delete_v4_cluster_hosts",
  "deploy_delete_v4_environment_hosts",
  "deploy_get_app",
  "deploy_get_app_log",
  "deploy_get_deploy_source_detail",
  "deploy_get_execution_params",
  "deploy_get_history_detail",
  "deploy_get_host_group",
  "deploy_get_last_record_detail",
  "deploy_get_runtime_variables",
  "deploy_get_status",
  "deploy_get_task",
  "deploy_get_template_detail",
  "deploy_get_v4_cluster",
  "deploy_get_v4_cluster_count",
  "deploy_get_v4_cluster_host",
  "deploy_get_v4_deploy_record",
  "deploy_get_v4_deploy_record_step_detail",
  "deploy_get_v4_deploy_record_step_logs",
  "deploy_get_v4_environment",
  "deploy_get_v4_environment_resource_detail",
  "deploy_import_hosts_to_environment",
  "deploy_list_app_host_groups",
  "deploy_list_app_operations_log",
  "deploy_list_apps",
  "deploy_list_deployment_units",
  "deploy_list_environment_hosts",
  "deploy_list_environments",
  "deploy_list_histories",
  "deploy_list_host_group_environments",
  "deploy_list_host_group_hosts",
  "deploy_list_host_groups",
  "deploy_list_system_configs",
  "deploy_list_tasks",
  "deploy_list_v4_applications",
  "deploy_list_v4_cluster_hosts",
  "deploy_list_v4_clusters",
  "deploy_list_v4_deploy_records",
  "deploy_list_v4_environment_applications",
  "deploy_list_v4_environment_hosts",
  "deploy_list_v4_environments",
  "deploy_list_v4_orchestrations",
  "deploy_list_variable_history",
  "deploy_list_variables",
  "deploy_modify_application",
  "deploy_pass_v4_manual_check",
  "deploy_query_variables",
  "deploy_refuse_v4_manual_check",
  "deploy_rerun_v4_deploy_record",
  "deploy_retry_v4_deploy_record",
  "deploy_rollback_app",
  "deploy_rollback_v4_deploy_record",
  "deploy_start_app",
  "deploy_stop_app"
].sort();

describe("deploy tool coverage manifest", () => {
  it("keeps the tested deploy tool manifest aligned with the exposed deploy tools", () => {
    expect(coveredDeployToolNames).toEqual([...deployToolNames].sort());
  });
});
